### ISSUE TITLE
can't fully accept incoming connection request

### ISSUE THREAD

**Issue by jdiercks** [wireapp/coax#5]
If I log on to Wire from a different client and issue a connection request to a user running in coax, the requesting user shows up in coax, and I can send a message to the requestor, but there is no obvious way to "accept" the connection request, so the non-coax client sees an incoming message but can't reply because the connection request is still pending.

Unfortunately I didn't capture any relevant debug output on this test. Will update later if I can re-create the conditions.

**Comment by twittner** [comment]
Connection request handling is in development. You may be able to see the connection request issued by another client if you click on the address book icon at the lower left of the main window. Below each contact there is a drop-down menu to change the connection status. New incoming requests should be in state "pending" and you can choose "accepted" to accept the request.

![connections](https://cloud.githubusercontent.com/assets/132165/23101581/2966a572-f697-11e6-9aaf-4e8ce44a7266.png)

**Comment by jdiercks** [comment]
ah, yes, that works. Thanks!
