### ISSUE TITLE
'Staging' connection URIs

### ISSUE THREAD

**Issue by flacks** [wireapp/coax#6]
For unoptimized builds, coax-actor is set to use https://staging-nginz-https.zinfra.io for the connection URL and https://staging-nginz-ssl.zinfra.io/await for the websocket. When connecting to those with a regular user account, I'm getting:

`ERRO failed to activate profile, error: actor error: error renewing access: error: invalid Credentials`

Are these URIs still accessible by regular users?

Connecting to the 'production' URIs works.

**Comment by neongreen** [comment]
No, staging is completely separate from production and has its own users database. Connecting to staging with a regular user account won't work.

**Comment by flacks** [comment]
Ok, thank you
